### ISSUE TITLE
I don't seem to be able to write bits and read them when the sizes are all correct (write and read bit size is the same).

### ISSUE THREAD

**Issue by kparmar1** [jinahya/bit-io2#3]
Hi,
I'm not sure if this is an error or that I'm using the lib incorrectly. If I write out some values and read them in again I get an error

```
 ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        StreamByteOutput streamByteOutput = new StreamByteOutput(() -> byteArrayOutputStream);
        BitOutput bitOutput = new BitOutputAdapter(() -> streamByteOutput);

        bitOutput.writeInt(5,10);
        bitOutput.writeInt(6,10);
        bitOutput.writeInt(3,2);
        bitOutput.writeInt(3,2);

        byte[] inputArray = byteArrayOutputStream.toByteArray();

        ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(inputArray);
        StreamByteInput streamByteInput = new StreamByteInput(() -> byteArrayInputStream);
        BitInput bitInput = new BitInputAdapter(() -> streamByteInput);

        System.out.println(bitInput.readInt(5));
        System.out.println(bitInput.readInt(6));
        System.out.println(bitInput.readInt(3));
        System.out.println(bitInput.readInt(3)); // <-- errors here with java.io.EOFException
```
It's simply writing out the sizes (known) and reading them back but you end up with an exception:

Exception in thread "main" java.io.EOFException: reached to an end
	at com.github.jinahya.bit.io.StreamByteInput.read(StreamByteInput.java:58)
	at com.github.jinahya.bit.io.StreamByteInput.read(StreamByteInput.java:34)
	at com.github.jinahya.bit.io.ByteInputAdapter.read(ByteInputAdapter.java:70)
	at com.github.jinahya.bit.io.BitInputAdapter.unsigned8(BitInputAdapter.java:116)
	at com.github.jinahya.bit.io.BitInputAdapter.unsigned8(BitInputAdapter.java:123)
	at com.github.jinahya.bit.io.BitInputAdapter.readInt(BitInputAdapter.java:80)
	at com.github.jinahya.bit.io.BitInputAdapter.readInt(BitInputAdapter.java:70)
	at com.github.jinahya.bit.io.BitInput.readInt(BitInput.java:193)

Thanks.

**Comment by onacit** [comment]
You have to align for octets.

```java
bitOutput.writeInt(5,10); // 5
bitOutput.writeInt(6,10); // 5 + 6 = 11
bitOutput.writeInt(3,2);  // 11 + 3 = 14
bitOutput.writeInt(3,2);  // 14 + 3 = 17 -> 7 more bits are required for 24 / 8 

int padded = bitOutput.align(1); // writes out some 0-bits to be aligned to 8-bit octets.
assert padded == 7;

byte[] inputArray = byteArrayOutputStream.toByteArray();
assert inputArray.length == 3; // without align(1), the length might be 2

System.out.println(bitInput.readInt(5));
System.out.println(bitInput.readInt(6));
System.out.println(bitInput.readInt(3));
System.out.println(bitInput.readInt(3));

int discarded = bitInput.align(1);
assert discarded == 7;
```

**Comment by kparmar1** [comment]
Thank you very much, appreciated. Kal.
